// edit.js — apply_edits: modify an existing deck two ways.
//
// (A) SPEC MODE — the reliable, full-power path. The deck was generated by this harness, so a
//     <deck>.pptx.spec.json sits next to it. We load that spec, apply edit operations to the
//     slides array, and rebuild a new .pptx. Every harness slide type can be fully edited.
//
// (B) LIVE MODE — for ANY .pptx (even ones not made here). Uses python-pptx to edit the file in
//     place: text replacement, slide deletion, reordering. Best-effort (no layout awareness).
//
// Slide addressing: every op may use { id: 's3' } (stable, preferred) OR { slide: 3 } (1-based).

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const schema = require('./schema');
const qa = require('./qa');

// ----------------------------- shared helpers -----------------------------

// Turn an anchor value (number = 1-based slide index, string = slide id) into a locator object.
function makeLocator(val) {
  if (val == null) throw new Error('edit needs an anchor (after/before/id/slide)');
  return typeof val === 'number' ? { slide: val } : { id: String(val) };
}

// Resolve a locator {id?|slide?} to a 0-based index into spec.slides. Throws if not found.
function locate(spec, op) {
  if (op.id != null) {
    const i = spec.slides.findIndex((s) => s.id === op.id);
    if (i < 0) throw new Error('no slide with id "' + op.id + '"');
    return i;
  }
  if (op.slide != null) {
    const i = Number(op.slide) - 1;
    if (i < 0 || i >= spec.slides.length) throw new Error('slide index ' + op.slide + ' out of range (1..' + spec.slides.length + ')');
    return i;
  }
  throw new Error('edit op needs "id" or "slide": ' + JSON.stringify(op));
}

// Insert/remove helpers operating on spec.slides in place.
function insertAt(spec, idx, slideSpec) {
  spec.slides.splice(Math.max(0, Math.min(idx, spec.slides.length)), 0, slideSpec);
}

function deepMerge(target, src) {
  for (const k of Object.keys(src || {})) {
    if (src[k] && typeof src[k] === 'object' && !Array.isArray(src[k]) && target[k] && typeof target[k] === 'object' && !Array.isArray(target[k])) {
      deepMerge(target[k], src[k]);
    } else {
      target[k] = src[k];
    }
  }
  return target;
}

// ----------------------------- (A) SPEC MODE -----------------------------

/**
 * Apply edit ops to a spec object (in place). Returns the spec.
 * Ops:
 *   {op:'setTitle', id|slide, title}
 *   {op:'set',      id|slide, field, value}            set/replace one top-level field
 *   {op:'patch',    id|slide, patch}                   deep-merge an object into the slide
 *   {op:'unset',    id|slide, field}
 *   {op:'replace',  id|slide, spec}                    replace the whole slide
 *   {op:'insert',   after|before, spec}                insert (after/before = id or 1-based slide)
 *   {op:'append',   spec}                              add at end
 *   {op:'delete',   id|slide}
 *   {op:'move',     id|slide, after|before}
 *   {op:'theme',    theme}            (spec-level)
 *   {op:'typography', typography}     (spec-level, merged)
 *   {op:'footerLabel', value}         (spec-level)
 *   {op:'title',    value}            (spec.deck)
 */
function applyEditsToSpec(spec, edits) {
  spec = spec || { slides: [] };
  spec.slides = Array.isArray(spec.slides) ? spec.slides.slice() : [];
  edits = Array.isArray(edits) ? edits : [edits];

  for (const e of edits) {
    switch (e.op) {
      case 'setTitle': spec.slides[locate(spec, e)].title = e.title; break;
      case 'set': spec.slides[locate(spec, e)][e.field] = e.value; break;
      case 'patch': deepMerge(spec.slides[locate(spec, e)], e.patch); break;
      case 'unset': delete spec.slides[locate(spec, e)][e.field]; break;
      case 'replace': spec.slides[locate(spec, e)] = Object.assign({ id: e.id }, e.spec); break;
      case 'insert': {
        const which = e.after !== undefined ? e.after : e.before;
        let idx = locate(spec, makeLocator(which));
        if (e.after !== undefined) idx += 1;
        insertAt(spec, idx, e.spec);
        break;
      }
      case 'append': spec.slides.push(e.spec); break;
      case 'delete': spec.slides.splice(locate(spec, e), 1); break;
      case 'move': {
        const from = locate(spec, e);
        const item = spec.slides.splice(from, 1)[0];
        const which = e.after !== undefined ? e.after : e.before;
        let idx = locate(spec, makeLocator(which));
        if (e.after !== undefined) idx += 1;
        insertAt(spec, idx, item);
        break;
      }
      case 'theme': spec.theme = e.theme; break;
      case 'typography': spec.typography = deepMerge(spec.typography || {}, e.typography); break;
      case 'footerLabel': spec.footerLabel = e.value; break;
      case 'title': spec.deck = e.value; break;
      default: throw new Error('unknown edit op "' + e.op + '"');
    }
  }
  return spec;
}

/**
 * specPath → apply edits → rebuild .pptx. Returns the output file path.
 * opts: { specPath, edits, out?, useImages=true, runQA=true, renderPreview=true }
 */
async function applyEdits(opts) {
  const build = require('../harness').build;
  const specPath = path.resolve(opts.specPath);
  const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
  applyEditsToSpec(spec, opts.edits);

  const v = schema.validateSlides(spec.slides);
  if (!v.ok) {
    const msg = 'edited spec failed validation:\n  ' + v.errors.join('\n  ');
    if (opts.strict !== false) throw new Error(msg);
    console.error(msg);
  }

  const out = opts.out || specPath.replace(/\.spec\.json$/, '.edited.pptx');
  await build({
    theme: spec.theme || 'healthcare',
    title: spec.deck,
    footerLabel: spec.footerLabel,
    typography: spec.typography,
    slides: spec.slides,
    out,
    useImages: opts.useImages !== false,
    runQA: opts.runQA !== false,
    renderPreview: opts.renderPreview !== false,
  });
  return out;
}

// ----------------------------- (B) LIVE MODE -----------------------------

/**
 * Edit ANY .pptx in place via python-pptx. Best-effort, no layout awareness.
 * opts: { pptx, out?, edits }
 * edits:
 *   {op:'replaceText', slide?, find, replace}   slide omitted → all slides
 *   {op:'deleteSlide', slide}                    1-based
 *   {op:'reorder', order:[3,1,2,...]}            1-based indices in new order
 */
function applyEditsLive(opts) {
  const src = path.resolve(opts.pptx);
  const out = path.resolve(opts.out || src.replace(/\.pptx$/i, '.edited.pptx'));
  if (!fs.existsSync(src)) throw new Error('pptx not found: ' + src);

  const py = qa.findPython();
  const script = `
import sys, json, copy
from pptx import Presentation
pptx_path, out_path, edits_json = sys.argv[1], sys.argv[2], sys.argv[3]
edits = json.loads(edits_json)
prs = Presentation(pptx_path)

def repl_text(tf, find, replace):
    hit = False
    for p in tf.paragraphs:
        full = ''.join(r.text for r in p.runs)
        if find in full:
            new = full.replace(find, replace)
            if p.runs:
                p.runs[0].text = new
                for r in p.runs[1:]:
                    r.text = ''
            hit = True
    return hit

def delete_slide(prs, idx):           # idx is 0-based
    rId = prs.slides._sldIdLst[idx].rId
    prs.part.drop_rel(rId)
    del prs.slides._sldIdLst[idx]

counts = {"text": 0, "deleted": 0}
for e in edits:
    op = e.get("op")
    if op == "replaceText":
        slides = []
        if "slide" in e:
            slides = [prs.slides[int(e["slide"]) - 1]]
        else:
            slides = list(prs.slides)
        for sl in slides:
            for sh in sl.shapes:
                if sh.has_text_frame:
                    if repl_text(sh.text_frame, e["find"], e["replace"]):
                        counts["text"] += 1
    elif op == "deleteSlide":
        delete_slide(prs, int(e["slide"]) - 1)
        counts["deleted"] += 1
    elif op == "reorder":
        order = [int(x) - 1 for x in e["order"]]
        new_lst = [prs.slides._sldIdLst[i] for i in order]
        lst = prs.slides._sldIdLst
        for child in list(lst):
            lst.remove(child)
        for child in new_lst:
            lst.append(child)
    else:
        raise SystemExit("unknown live op: " + str(op))

prs.save(out_path)
print(json.dumps(counts))
`;
  const res = spawnSync(py, ['-c', script, src, out, JSON.stringify(opts.edits || [])], {
    env: { ...process.env, PYTHONUTF8: '1' }, encoding: 'utf8', timeout: 120000,
  });
  if (res.status !== 0) {
    const err = (res.stderr || res.stdout || '').trim();
    throw new Error('live edit failed (python-pptx):\n' + err.split('\n').slice(-12).join('\n'));
  }
  let counts = {};
  try { counts = JSON.parse((res.stdout || '').trim().split('\n').pop()); } catch (e) { /* ignore */ }
  return { out, counts };
}

module.exports = { applyEditsToSpec, applyEdits, applyEditsLive, locate, deepMerge };
